[global]
# info = [ {tag="mameversion", value="0229"} ]
mraauthor=["jotego","atrac17"]

[features]
# ddr = true
#beta = true
# qsound=true
debug=true
# NVRAM = 64kB+10kB+1 byte
nvram = 75777

[parse]
sourcefile="segas16b.cpp"
# Games with S16A parents need explicit listing
# the description is used to make the alternate folders
parents= [
    {name="shinobi", description="Shinobi"},
    {name="afighter", description="Action Fighter"},
    {name="sdi", description="SDI"},
    {name="tetris", description="Tetris"}
]

[parse.skip]
descriptions = [ "16A", "Taito" ]
setnames = [ "lockonph" ]
# bootlegs = true # do not process bootlegs

[buttons]
#Sega System 16B
#Sega System 16B - Charon
#Sega System 16C
#Sega System 16B - Korean
core=4 # max number of buttons supported by the core
names = [
    { machine="aceattac", names="none" },
    { machine="afighter", names="Shot,Special Weapon" },
    { machine="aliensyn", names="Shot" },
    { machine="altbeast", names="Punch,Kick,Jump" },
    { machine="aurail",   names="Rapid Shot,Kite/Turn,Shield" },
    { machine="bayroute", names="Shot,Jump,Select" },
    { machine="bullet",   names="Shot (Up),Shot (Right),Shot (Behind),Shot (Left)" },
    { machine="cotton",   names="Shoot/Magic,Bomb/Nymphs" },
    { machine="ddux",     names="Shot,Jump" },
    { machine="dunkshot", names="Shot,Pass" },
    { machine="eswat",    names="Shot,Jump,Special Weapons" },
    { machine="exctleag", names="Change,Select,Chase" },
    { machine="fpoint",   names="Rotate,Rotate,Rotate" },
    { machine="goldnaxe", names="Attack,Jump,Magic" },
    { machine="hwchamp",  names="none" },
    { machine="mvp",      names="Change,Select,Chase" },
    { machine="passsht",  names="Flat,Slice,Lob,Top Spin" },
    { machine="riotcity", names="Attack,Jump" },
    { machine="ryukyu",   names="Cancel,Decide" },
    { machine="sdi",      names="Shot" },
    { machine="sonicbom", names="Shot,Super Shot" },
    { machine="shinobi",  names="Shuriken,Jump,Magic" },
    { machine="sjryuko",  names="none" },
    { machine="suprleag", names="Change,Select,Chase" },
    { machine="tetris",   names="Rotate,Rotate,Rotate" },
    { machine="timescan", names="L. Flipper/Ball Start,R. Flipper/Lane Shift" },
    { machine="toryumon", names="Block Turn" },
    { machine="tturf",    names="Punch,Kick,Jump" },
    { machine="ultracin", names="Attack" },
    { machine="wb3",      names="Shot,Jump" },
    { machine="wrestwar", names="Punch,Kick" },
    { machine="fantzn2x", names="Shot,Bomb" },
    { machine="atomicp",  names="Rotate" },
    { machine="snapper",  names="Left,Right,Shot" },
    { machine="lockonph", names="Shot,Bomb" },
    { machine="dfjail",   names="Assault Rifle,Jump,R.P.G" }
]

[rbf]
name="jts16b"
# dev = [
#     { dev="fd1094", rbf="jts16a2" },
#     { dev="8751", rbf="jts16a1"}
# ]

[dipsw]
delete = [ "Unused", "Unknown" ]
# base = 16

[header]
len=32
fill=0
dev = [
    { byte=0x10, dev="fd1089a", value=1 },
    { byte=0x10, dev="fd1089b", value=2 },
    { byte=0x11, dev="fd1094",  value=1 },
    { byte=0x12, dev="mc8123",  value=1 },
    { byte=0x13, dev="i8751",   value=1 }
]
# init_generic_5521 = 0
# init_hwchamp_5521 = 1
# init_altbeasj_5521 = 2
# init_altbeas4_5521 = 3
# init_shinobi4_5521 = 4
# init_generic_korean = 8
# init_snapper = 9
# init_lockonph = 0xa
# init_generic_5358 = 0x10
# init_generic_5358_small = 0x11
# init_sdi_5358_small = 0x12
# init_passshtj_5358  = 0x13
# init_dunkshot_5358_small = 0x14
# init_exctleag_5358 = 0x15
# init_aliensyn7_5358_small = 0x16
# init_aceattac_5358 = 0x17
# init_cencourt_5358 = 0x18
# init_defense_5358_small = 0x19
# init_shinobi3_5358 = 0x1a
# init_sjryuko_5358_small = 0x1b
# init_timescan_5358_small = 0x1c
# init_generic_5797 = 0x20
# init_generic_5704 = 0x40
# init_tturf_5704 = 0x41
# init_wb3_5704 = 0x42
# init_generic_bootleg = 0x80
machine = [
    { machine="aceattac", byte=0x18, value=0x17 },
    { machine="aliensyn", byte=0x18, value=0x11 },
    { machine="aliensyn7", byte=0x18, value=0x16 },
    { machine="aliensyn3", byte=0x18, value=0x11 },
    { machine="aliensynj", byte=0x18, value=0x11 },
    { machine="afightere", byte=0x18, value=0x11 },
    { machine="afighterf", byte=0x18, value=0x11 },
    { machine="afighterg", byte=0x18, value=0x11 },
    { machine="afighterh", byte=0x18, value=0x11 },
    { machine="altbeast", byte=0x18, value=0 },
    { machine="altbeastj", byte=0x18, value=2 },
    { machine="altbeast6", byte=0x18, value=0 },
    { machine="altbeast5", byte=0x18, value=0 },
    { machine="altbeast4", byte=0x18, value=3 },
    { machine="altbeastj3", byte=0x18, value=0 },
    { machine="altbeast2", byte=0x18, value=3 },
    { machine="altbeastj1", byte=0x18, value=0 },
    { machine="aurail", byte=0x18, value=0x40 },
    { machine="aurail1", byte=0x18, value=0x40 },
    { machine="aurailj", byte=0x18, value=0x40 },
    { machine="bayroute", byte=0x18, value=0x40 },
    { machine="bayroutej", byte=0x18, value=0x40 },
    { machine="bayroute1", byte=0x18, value=0x10 },
    { machine="bullet", byte=0x18, value=0x11 },
    { machine="cotton", byte=0x18, value=0x40 },
    { machine="cottonu", byte=0x18, value=0x40 },
    { machine="cottonj", byte=0x18, value=0x40 },
    { machine="cottonja", byte=0x18, value=0x40 },
    { machine="ddux", byte=0x18, value=0 },
    { machine="dduxj", byte=0x18, value=0 },
    { machine="ddux1", byte=0x18, value=0x40 },
    { machine="dunkshot", byte=0x18, value=0x14 },
    { machine="dunkshota", byte=0x18, value=0x14 },
    { machine="dunkshoto", byte=0x18, value=0x14 },
    { machine="eswat", byte=0x18, value=0x20 },
    { machine="eswatu", byte=0x18, value=0x20 },
    { machine="eswatj", byte=0x18, value=0x20 },
    { machine="eswatj1", byte=0x18, value=0x40 },
    { machine="exctleag", byte=0x18, value=0x15 },
    { machine="fpoint", byte=0x18, value=0x10 },
    { machine="fpoint1", byte=0x18, value=0x40 },
    { machine="goldnaxe", byte=0x18, value=0x20 },
    { machine="goldnaxeu", byte=0x18, value=0x20 },
    { machine="goldnaxej", byte=0x18, value=0x40 },
    { machine="goldnaxe3", byte=0x18, value=0x40 },
    { machine="goldnaxe2", byte=0x18, value=0x40 },
    { machine="goldnaxe1", byte=0x18, value=0x20 },
    { machine="hwchamp", byte=0x18, value=1 },
    { machine="hwchampj", byte=0x18, value=1 },
    { machine="mvp", byte=0x18, value=0x20 },
    { machine="mvpj", byte=0x18, value=0x40 },
    { machine="passsht", byte=0x18, value=0x10 },
    { machine="passshta", byte=0x18, value=0x13 },
    { machine="passshtj", byte=0x18, value=0x13 },
    { machine="cencourt", byte=0x18, value=0x18 },
    { machine="riotcity", byte=0x18, value=0x40 },
    { machine="ryukyu", byte=0x18, value=0x40 },
    { machine="ryukyua", byte=0x18, value=0x40 },
    { machine="defense", byte=0x18, value=0x19 },
    { machine="sdib", byte=0x18, value=0x19 },
    { machine="sdibl", byte=0x18, value=0x12 },
    { machine="shinobi6", byte=0x18, value=0 },
    { machine="shinobi5", byte=0x18, value=0x10 },
    { machine="shinobi4", byte=0x18, value=4 },
    { machine="shinobi3", byte=0x18, value=0x1a },
    { machine="shinobi2", byte=0x18, value=0x10 },
    { machine="sonicbom", byte=0x18, value=0x10 },
    { machine="sjryuko", byte=0x18, value=0x1b },
    { machine="suprleag", byte=0x18, value=0x15 },
    { machine="tetris2", byte=0x18, value=0x40 },
    { machine="tetris1", byte=0x18, value=0x11 },
    { machine="timescan", byte=0x18, value=0x1c },
    { machine="toryumon", byte=0x18, value=0x20 },
    { machine="tturf", byte=0x18, value=0x41 },
    { machine="tturfu", byte=0x18, value=0x10 },
    { machine="ultracin", byte=0x18, value=0x20 },
    { machine="wb3", byte=0x18, value=0x42 },
    { machine="wb34", byte=0x18, value=0x40 },
    { machine="wb33", byte=0x18, value=0x40 },
    { machine="wb32", byte=0x18, value=0x10 },
    { machine="wrestwar", byte=0x18, value=0x40 },
    { machine="wrestwar2", byte=0x18, value=0x40 },
    { machine="wrestwar1", byte=0x18, value=0x40 },
    { machine="fantzn2x", byte=0x18, value=0x40 },
    { machine="fantzn2xp", byte=0x18, value=0x40 },
    { machine="fantzoneta", byte=0x18, value=0x40 },
    { machine="atomicp", byte=0x18, value=8 },
    { machine="snapper", byte=0x18, value=9 },
    { machine="lockonph", byte=0x18, value=0xa },
    { machine="dfjail", byte=0x18, value=  8 },
    { machine="shinobi2d", byte=0x18, value=0x10 },
    { machine="fpointd", byte=0x18, value=0x10 },
    { machine="fpoint1d", byte=0x18, value=0x40 },
    { machine="tetris2d", byte=0x18, value=0x40 },
    { machine="tetris1d", byte=0x18, value=0x11 },
    { machine="dduxd", byte=0x18, value=0 },
    { machine="dduxjd", byte=0x18, value=0 },
    { machine="altbeast5d", byte=0x18, value=0 },
    { machine="altbeastj3d", byte=0x18, value=0 },
    { machine="aurail1d", byte=0x18, value=0x40 },
    { machine="aurailjd", byte=0x18, value=0x40 },
    { machine="mvpd", byte=0x18, value=0x20 },
    { machine="mvpjd", byte=0x18, value=0x40 },
    { machine="cottond", byte=0x18, value=0x40 },
    { machine="cottonud", byte=0x18, value=0x40 },
    { machine="cottonjad", byte=0x18, value=0x40 },
    { machine="cottonjd", byte=0x18, value=0x40 },
    { machine="bayrouted", byte=0x18, value=0x40 },
    { machine="bayroutejd", byte=0x18, value=0x40 },
    { machine="exctleagd", byte=0x18, value=0x15 },
    { machine="sonicbomd", byte=0x18, value=0x10 },
    { machine="ryukyud", byte=0x18, value=0x40 },
    { machine="hwchampjd", byte=0x18, value=1 },
    { machine="bulletd", byte=0x18, value=0x11 },
    { machine="eswatd", byte=0x18, value=0x20 },
    { machine="eswatud", byte=0x18, value=0x20 },
    { machine="eswatjd", byte=0x18, value=0x20 },
    { machine="eswatj1d", byte=0x18, value=0x40 },
    { machine="goldnaxeud", byte=0x18, value=0x20 },
    { machine="goldnaxe3d", byte=0x18, value=0x40 },
    { machine="goldnaxe1d", byte=0x18, value=0x20 },
    { machine="goldnaxejd", byte=0x18, value=0x40 },
    { machine="passshtd", byte=0x18, value=0x10 },
    { machine="passshtad", byte=0x18, value=0x13 },
    { machine="passshtjd", byte=0x18, value=0x13 },
    { machine="wb34d", byte=0x18, value=0x40 },
    { machine="wb33d", byte=0x18, value=0x40 },
    { machine="wb32d", byte=0x18, value=0x10 },
    { machine="wrestwar2d", byte=0x18, value=0x40 },
    { machine="wrestwar1d", byte=0x18, value=0x40 },
    { machine="sdibl2", byte=0x18, value=0x12 },
    { machine="sdibl3", byte=0x18, value=0x12 },
    { machine="sdibl4", byte=0x18, value=0x12 },
    { machine="sdibl5", byte=0x18, value=0x12 },
    { machine="sdibl6", byte=0x18, value=0x12 }
]

# Sample header data
# data=[
#     { pointer=8,    data=[0xff, 0x43, 0x34] },
#     { pointer=0x10, data=[0xca, 0xfe] }
# ]


[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu",       width=16, reverse=true },
    { name="mcu",           start=$MCU_START, len=0x1000 },
    { name="soundcpu",      start=$BA1_START },
    { name="gfx1",          start=$BA2_START, frac={ bytes=1, parts=4}, sort_byext=true, len=0x100000 },
    { name="sprites",       start=$BA3_START, width=16, reverse=true },
    { name="maincpu:key",   start=$MAINKEY_START, len=0x2000 },
    { name="soundcpu:key",  start=$SNDKEY_START, len=0x2000 },
    { name="fd1089",        start=$FD1089_START },
    { name="plds",          skip=true }
]
# { name="myregion", reorder=[3,2,1,0] } # reorder files inside a region
order = [
    "maincpu", "soundcpu", "gfx1",
    "sprites", "mcu", "maincpu:key", "soundcpu:key"
]
splits = [
    { machine="riotcity", region="sprites", offset=0x100000 },
    { machine="goldnaxe", region="sprites", offset=0x100000 },
    { setname="eswat",    region="sprites", offset=0x100000 },
    { setname="mvp",      region="sprites", offset=0x100000 },
    { machine="ultracin", region="sprites", offset=0x100000 },
    # Do not split
    { setname="eswatj1", offset=0  },
    { setname="eswatj1d", offset=0 }
]
